export 'speciality/speciality.dart';
export 'doctor/artisan_list.dart';
export 'doctor/ArtisanTimeSlot.dart';
export 'doctor/Artisan_profile.dart';
export 'review/review.dart';
export 'doctor/consultation_detail.dart';
// export 'payment/payment.dart';
// export 'lab/lab_list.dart';
// export 'lab/lab.dart';
export 'appointment/appointment.dart';
// export 'chat/chat_list.dart';
// export 'chat/chat.dart';
export 'profile/profile.dart';
export 'patient/patient_directory.dart';
// export 'about/about_us.dart';
export 'profile/edit_profile.dart';
// export 'login_signup/login.dart';
// export 'login_signup/otp.dart';
// export 'login_signup/register.dart';
// export 'notifications/notifications.dart';
export 'splashScreen.dart';
export 'search/search.dart';